site_name: django async extensions
repo_url: https://github.com/amirreza8002/django-async-extensions

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
      base_path: ["."]

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - python
    - pycon

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    - media: "(prefers-color-scheme: light)"
      schema: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference


