site_name: django async extensions
repo_url: https://github.com/amirreza8002/django-async-extensions
theme:
  name: mkdocs
  highlightjs: true
  user_color_mode_toggle: true
  hljs_languages:
    - python
    - pycon
